#!/usr/bin/env node

const fs = require("fs");
const path = require("path");

const ZINES_DIR = path.join(__dirname, "img", "zines");
const OUT_FILE = path.join(__dirname, "data.js");

const IMAGE_EXTS = new Set([".jpg", ".jpeg", ".png", ".webp"]);

function titleFromFolder(name) {
  return name.replace(/[-_]/g, " ").replace(/^\w/, (c) => c.toUpperCase());
}

function isImage(file) {
  return IMAGE_EXTS.has(path.extname(file).toLowerCase());
}

function encodePath(filePath) {
  return filePath.split("/").map(encodeURIComponent).join("/");
}

const folders = fs
  .readdirSync(ZINES_DIR, { withFileTypes: true })
  .filter((d) => d.isDirectory())
  .map((d) => d.name)
  .sort();

const zines = folders.map((folder) => {
  const dir = path.join(ZINES_DIR, folder);
  const files = fs
    .readdirSync(dir)
    .filter(isImage)
    .sort((a, b) => {
      const numA = parseInt(a.match(/(\d+)/)?.[1] || "0", 10);
      const numB = parseInt(b.match(/(\d+)/)?.[1] || "0", 10);
      return numA - numB;
    });

  const hasCover = files.some((f) => f.toLowerCase().startsWith("cover"));
  const coverFile = hasCover
    ? files.find((f) => f.toLowerCase().startsWith("cover"))
    : files[0];

  const photos = files
    .filter((f) => !f.toLowerCase().startsWith("cover"))
    .map((f) => encodePath(`img/zines/${folder}/${f}`));

  const cover = coverFile ? encodePath(`img/zines/${folder}/${coverFile}`) : photos[0];

  return { id: folder, title: titleFromFolder(folder), cover, photos };
}).filter((z) => z.photos.length > 0);

const lines = zines.map((z) => {
  const photoLines = z.photos.map((p) => `      { src: "${p}" },`).join("\n");
  return `  {
    id: "${z.id}",
    title: "${z.title}",
    cover: "${z.cover}",
    photos: [
${photoLines}
    ],
  },`;
});

const output = `/* Auto-generated by build-data.js — do not edit by hand */

const ZINES = [
${lines.join("\n")}
];
`;

fs.writeFileSync(OUT_FILE, output);
console.log(`Generated ${OUT_FILE} with ${zines.length} albums.`);
